#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################
# Simulation script for COMPONENT: forward_kernel
set -e
SWD="$(dirname $(readlink -e $0))"
cd ${SWD}
if [ ! -z "$APPDIR" ]; then LD_LIBRARY_PATH=""; fi

CC="/opt/clang-16/bin/clang"
SYS_ELF="HLS_output/simulation/testbench"
SIM_DIR="HLS_output/simulation"
OUT_LVL="3"

### Do not edit below

BEH_DIR="HLS_output/beh_sim"
M_IPC_FILENAME="${SIM_DIR}/panda_sock"
export VM_PARALLEL_BUILDS=1
BEH_CC="${CC}"
obj_dir="${BEH_DIR}/verilator_obj"

make -f /opt/panda/share/panda/libmdpi/Makefile.mk \
  SIM_DIR="${SIM_DIR}" BEH_DIR="${BEH_DIR}" \
  TOP_FNAME="forward_kernel" \
  MTOP_FNAME="__m_forward_kernel" \
  MPPTOP_FNAME="__m_pp_forward_kernel" \
  CC="${CC}" \
  BEH_CC="${BEH_CC}" \
  CFLAGS=" -O2  -fno-builtin-bcmp -fno-builtin-memcpy -fno-builtin-memmove -fno-builtin-memset -ffp-contract=off -finline-functions -fno-slp-vectorize -fno-stack-protector -fno-vectorize -fwrapv  --std=gnu11 -D__BAMBU__ -Wuninitialized  -lm  -D__NO_INLINE__  -m32  -fwrapv -flax-vector-conversions -msse2 -fno-strict-aliasing -D__builtin_bambu_time_start\(\)= -D__builtin_bambu_time_stop\(\)= -D__BAMBU_SIM__ -isystem /opt/panda/share/panda/libmdpi/include " \
  BEH_CFLAGS="-DVERILATOR -isystem $(dirname $(which verilator))/../share/verilator/include/vltstd -isystem /opt/panda/share/panda/libmdpi/include -D__M_IPC_FILENAME=\\\"${M_IPC_FILENAME}\\\" -D__M_OUT_LVL=${OUT_LVL} -D__M32 -O2" \
  TB_CFLAGS="" \
  SRCS="input.ll" \
  WRAPPER_SRC="${SIM_DIR}/mdpi_wrapper.cpp" \
  PP_SRC="" \
  TB_SRCS="../../forward_kernel_testbench.c" \
  -j ${OMP_NUM_THREADS:-128}

verilator --cc --exe --Mdir ${obj_dir} -Wno-fatal -Wno-lint -sv  +define+__M32 +define+__BAMBU_SIM__ ${BEH_DIR}/libmdpi.so -O3 --unroll-count 10000 --output-split-cfuncs 3000  --output-split-ctrace 3000 --x-assign fast --x-initial fast --noassert forward_kernel.v HLS_output/simulation/bambu_testbench.v ${BEH_DIR}/libmdpi.so HLS_output/beh_sim/sim_main.cpp --top-module bambu_testbench
if [ $? -ne 0 ]; then exit 1; fi

ln -sf ../../ ${obj_dir}/HLS_output || true
make -C ${obj_dir}  -j 128 OPT="-fstrict-aliasing -DVCD_OUT_DIR="${SIM_DIR}"" -f Vbambu_testbench.mk Vbambu_testbench

export M_IPC_SIM_CMD="${obj_dir}/Vbambu_testbench 2>&1 | tee ${BEH_DIR}/forward_kernel_verilator.log; exit \${PIPESTATUS[0]};"

if [ -f ${SYS_ELF} ]; then
  function get_class { readelf -h $1 | grep Class: | sed -E 's/.*Class:\s*(\w+)/\1/'; }
  sys_elf_class="$(get_class ${SYS_ELF})"
  driver_elf_class="$(get_class ${SIM_DIR}/libmdpi_driver.so)"
  if [ "${sys_elf_class}" != "${driver_elf_class}" ]; then
    echo "ERROR: Wrong system application ELF class: ${sys_elf_class} != ${driver_elf_class}"; exit 1;
  fi
  echo "Launch user testbench with args: $@"
  ${SYS_ELF} "$@" 2>&1 | tee ${SIM_DIR}/$(basename ${SYS_ELF}).log
  exit ${PIPESTATUS[0]}
fi
exit -1

