#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################
# Synthesis script for COMPONENT: forward_kernel
SWD="$(dirname $(readlink -e $0))"

# STEP: xst
cd $SWD
xst -ifn HLS_output/Synthesis/xst/xst.tcl -intstyle silent -ofn HLS_output/Synthesis/xst/forward_kernel.log

# STEP: ngdbuild
cd $SWD
ngdbuild -quiet -intstyle silent -dd HLS_output/Synthesis/ngdbuild -nt timestamp -p xc7z020clg484-1 -uc HLS_output/Synthesis/ucf/forward_kernel.ucf HLS_output/Synthesis/xst/forward_kernel.ngc HLS_output/Synthesis/ngdbuild/forward_kernel.ngd
if [ $? -ne 0 ]; then exit 1; fi

# STEP: map
cd $SWD
map -w -u -detail -register_duplication on -logic_opt on -ol high -pr off -bp -timing -mt 2 -ir off -lc auto -p xc7z020clg484-1 -o HLS_output/Synthesis/map/forward_kernel.ncd HLS_output/Synthesis/ngdbuild/forward_kernel.ngd HLS_output/Synthesis/map/forward_kernel.pcf

# STEP: par
cd $SWD
par -w -ol high -nopad -mt 4 HLS_output/Synthesis/map/forward_kernel.ncd HLS_output/Synthesis/par/forward_kernel.ncd HLS_output/Synthesis/map/forward_kernel.pcf

# STEP: trce
cd $SWD
trce -xml HLS_output/Synthesis/trce/post_forward_kernel.twx -o HLS_output/Synthesis/trce/post_forward_kernel.twr -e 1 -u -a -ucf HLS_output/Synthesis/ucf/forward_kernel.ucf HLS_output/Synthesis/par/forward_kernel.ncd HLS_output/Synthesis/map/forward_kernel.pcf

